"""add contact_attempts to dialog_sessions

Revision ID: 412db7507c59
Revises: 8cd1e0d95b7a
Create Date: 2026-06-19 19:46:51.074574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412db7507c59'
down_revision: Union[str, Sequence[str], None] = '8cd1e0d95b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog_sessions', sa.Column('contact_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialog_sessions', 'contact_attempts')
    # ### end Alembic commands ###
