"""add last_delivery_error to leads

Revision ID: a8ffd1220905
Revises: 21a80ea32600
Create Date: 2026-06-21 11:37:33.717280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8ffd1220905"
down_revision: Union[str, Sequence[str], None] = "21a80ea32600"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("leads", sa.Column("last_delivery_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leads", "last_delivery_error")
    # ### end Alembic commands ###
