"""soft delete: deleted_at + partial unique users

Revision ID: ee6e74045934
Revises: 412db7507c59
Create Date: 2026-06-19 21:17:07.833360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee6e74045934"
down_revision: Union[str, Sequence[str], None] = "412db7507c59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dialog_sessions",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "leads", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "messages", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("uq_users_channel_anonymous_id"), "users", type_="unique")
    op.create_index(
        "uq_users_channel_anonymous_id",
        "users",
        ["channel", "anonymous_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_channel_anonymous_id",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_users_channel_anonymous_id"),
        "users",
        ["channel", "anonymous_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "deleted_at")
    op.drop_column("messages", "deleted_at")
    op.drop_column("leads", "deleted_at")
    op.drop_column("dialog_sessions", "deleted_at")
    # ### end Alembic commands ###
